[project]
enable_telemetry = false
name = "MedDesk AI"
description = "AI-powered medical assistant for healthcare"

[UI]
name = "MedDesk AI"
description = "Your virtual health assistant"
default_collapse_content = true
layout = "wide"
custom_css = "/public/custom.css"

[UI.theme]
layout = "wide"

[database]
type = "none"
